- Dockerfile
1. Clean up caches after installing packages
2. Ensure proper permission for renovate home
3. Install rpm-lockfile-prototype globally
> Fix package installations

- Dockerfile
Mintmaker doesn't detect rpm lockfile changes when image tag and digest are both provided. This is due to some skopeo known issue. This was resolved in the rpm lockfile new release. Let's move to that version.
> Update rpm lockfile script to the newer version

- .tekton/mintmaker-renovate-image-pull-request.yaml
- .tekton/mintmaker-renovate-image-push.yaml
The container build task in the PipelineRuns can take a long time to finish. The default 1h timeout is insufficient for running the remaining tasks. Updated the timeout to 1h30m to ensure successful completion.
> Increase PipelineRun timeout

- Dockerfile
Some small modifications were required. The `rpm-lockfile-prototype` will use python3.9 because `python3-dnf` is only built for this python version. The package managers are installed using `pip3.12` and forced to use python3.12. Also, `podman` is removed since only `skopeo` is now used.
> Use ubi9-minimal as a base image

- Dockerfile
Some repos have `context` specified in their `rpms.in.yaml` but v0.2.0 doesn't support that yet, but in will still be overridden in the `rpm` manager until the command line option `-f` is removed.
> Update to rpm-lockfile-prototype v0.5.1

- Dockerfile
This fixes one important issue that was discovered today: https://github.com/konflux-ci/rpm-lockfile-prototype/pull/29
> Update to rpm-lockfile-prototype v0.6.0

- Dockerfile
This version contains https://github.com/konflux-ci/rpm-lockfile-prototype/pull/32 which is needed for CWFHEALTH-3245
> Update to rpm-lockfile-prototype v0.7.0

- .tekton/mintmaker-renovate-image-pull-request.yaml
- .tekton/mintmaker-renovate-image-push.yaml
TaskRun has a default timeout of 1 hour. Occasionally, the build-container task may fail due to this timeout, especially if the COMMIT/push process takes a long time.
> Increase the timeouts for the pipeline and the build-container task

- Dockerfile
Rebased on the upstream Renovate project on the 38.55.2 tag. Also changed the version suffix from `-custom` to `-rpm` to better reflect why it's there. And this image builds from the branch `rpm-lockfiles-new` so we have a fallback in case something doesn't work (but it appears everything is ok).
Edit: this will also include the latest commit in the `rpm` manager, where the `-f Dockerfile` or `-f Containerfile` is no longer specified: https://github.com/redhat-exd-rebuilds/renovate/commit/193e711c44397c23c7931963e7d3e2c707c3d2bf
> Update base Renovate to 38.55.2

- README.md
There used to be some documentation here:
https://redhat-exd-rebuilds.github.io/mintmaker-docs/
Which is being moved to the official Konflux documentation. We still have some pages about the dev docs.
Let's move here whatever is about the Dockerfile.
ref: CWFHEALTH-3218
> Move docs about Dockerfile to the README

- Dockerfile
This update was requested by the OSCI team.
I quickly checked that building the new image works fine.
> Update rpm-lockfile-script version (v0.9.0)

- Dockerfile
This commit enables `uv` and `hatch`, which are used by the `pep621` manager in renovate.
This was a suggestion in https://github.com/konflux-ci/mintmaker/pull/92.
> Install dependencies for pep621 python manager

- .tekton/mintmaker-renovate-image-pull-request.yaml
- .tekton/mintmaker-renovate-image-push.yaml
Starting from Nov 1st, EC began enforcing the required `rpms-signature-scan` task.
> Add required rpms-signature-scan task

- Dockerfile
Konflux enforces RPM signature checks and, by default, only allows RPMs signed by Red Hat release keys. You can update the ReleasePlanAdmission (RPA) to ignore this check or permit other keys. However, installing via tarball is a simpler alternative.
> Install tekton cli with tarball

- Dockerfile
pip-tools provides `pip-compile` cli, required by `pip-compile` manager enabled in https://github.com/konflux-ci/mintmaker/pull/92/files
> install pip-tools for pip-compile manager

- Dockerfile
This version includes caching of rpmdb
> Update to rpm-lockfile-prototype v0.10.0

- Dockerfile
I recently rebased the `repm-lockfile-new` branch in our fork of Renovate on top of the `38.132.0` tag. In other words, we are ready to build version 38.132.0-rpm.
I built this image manually and made manual tests in a few repositories. So far, everything seems to work fine, we do not need a new node version for what it seems.
I'll watch the stage runs after this change is merged.
> Update Renovate version label

- .github/renovate.json
Tested, proposes diffs as
```diff
-ARG RPM_LOCKFILE_PROTOTYPE_VERSION=0.10.0
+ARG RPM_LOCKFILE_PROTOTYPE_VERSION=0.11.0
```
> Set up Renovate to update rpm-lockfile-prototype version

- .github/renovate.json
The tekton manager only runs on Saturdays in latest global schedules, so there's no need to specify a custom schedule. Defining a schedule outside the global schedule window could also prevent pull requests from being created or merged.
> Update tekton manager schedule

- Dockerfile
This uses `pyenv`'s internals to do what `pyenv install` would normally do, but that way we wouldn't be able to specify the install root (or prefix).
- `pyenv latest -f -k 3.13` will check which minor version is the newest for 3.13 (currently 3.13.1)
- The Python is installed into `~/pythonX.YY` so that we can easily add that into `$PATH`. We cannot dynamically modify `$PATH`, so we need to make a workaround like this.
- The `python-build` is a `pyenv` plugin that's part of the installation, but we need to invoke it directly to be able to change the install root
I tested this on a reported repo with poetry that wants to use 3.13 and Renovate can update the lock file correctly after this change.
> Add python 3.13 and 3.10 via pyenv

- Dockerfile
STONEBLD-2824
The pipeline-migration-tool requires yq to execute task migrations.
> Install yq

- Dockerfile
This change allows Renovate to _renovate_ different versions of Go. There was also a suggestion to predownload different toolchains, however when i tested this agains dependency from go1.21 and go1.23 it did not redownload anything, can I skip it?
> Override ubi9's gotoolchain from local to auto

- .github/renovate.json
- Dockerfile
1. Add RENOVATE_REVISION ARG to Dockerfile to pin the exact commit from the fork that supports RPM lockfile and vulnerability alerts.
2. Configure renovate to update the pinned commit hash in Dockerfile.
> Build renovate from specific commit hash

- Dockerfile
For projects based on postgres
> Add libpq-devel to the image to allow building psycopg2 from source

- .tekton/mintmaker-renovate-image-pull-request.yaml
- .tekton/mintmaker-renovate-image-push.yaml
- Dockerfile
1. Add new mandatory sast tasks: sast-shell-check, sast-unicode-check
2. Add new task: build-image-index, the new sast tasks depend on the build-image-index task
3. Replace many references to build-container with build-image-index throughout the pipeline
4. Add new task push-dockerfile to align with standard pipeline
This commit also includes some minor adjustments, as it is updated based on the latest standard pipelines.
https://issues.redhat.com/browse/KONFLUX-2264
> Add shell and unicode sast pipeline tasks

- Dockerfile
For projects that require building Python wheels like pykerberos
> Add krb5-devel

- Dockerfile
This is required to run `jb update` which currently fails for a bunch of user repos.
> Add jsonnet-bundler binary

- Dockerfile
The `--system-site-packages` flag ensures that `rpm-lockfile-prototype` can use `python3-dnf` from `/usr/lib/python3.xx`
> Use pipx to install rpm-lockfile-prototype
